### ISSUE TITLE
java.lang.NoSuchMethodError: com.twitter.finagle.util.DefaultTimer$.twitter() on Todo example

### ISSUE THREAD

**Issue by mfirry** [vkostyukov/finch-101#1]
```
Enter number: 7

[info] Running i.f.workshop.finch.Todo
I 1112 14:09:55.531 THREAD30: /admin => com.twitter.server.handler.SummaryHandler
I 1112 14:09:55.532 THREAD30: /admin/server_info => com.twitter.finagle.Filter$$anon$2
I 1112 14:09:55.532 THREAD30: /admin/contention => com.twitter.finagle.Filter$$anon$2
I 1112 14:09:55.533 THREAD30: /admin/threads => com.twitter.server.handler.ThreadsHandler
I 1112 14:09:55.535 THREAD30: /admin/threads.json => com.twitter.server.handler.ThreadsHandler
I 1112 14:09:55.535 THREAD30: /admin/announcer => com.twitter.finagle.Filter$$anon$2
I 1112 14:09:55.535 THREAD30: /admin/dtab => com.twitter.finagle.Filter$$anon$2
I 1112 14:09:55.535 THREAD30: /admin/pprof/heap => com.twitter.server.handler.HeapResourceHandler
I 1112 14:09:55.536 THREAD30: /admin/pprof/contention => com.twitter.server.handler.ProfileResourceHandler
I 1112 14:09:55.536 THREAD30: /admin/pprof/profile => com.twitter.server.handler.ProfileResourceHandler
I 1112 14:09:55.536 THREAD30: /admin/ping => com.twitter.server.handler.ReplyHandler
I 1112 14:09:55.536 THREAD30: /admin/shutdown => com.twitter.server.handler.ShutdownHandler
I 1112 14:09:55.537 THREAD30: /admin/events => com.twitter.server.handler.EventsHandler
I 1112 14:09:55.536 THREAD30: /admin/tracing => com.twitter.server.handler.TracingHandler
I 1112 14:09:55.537 THREAD30: /admin/events/ => com.twitter.server.handler.EventRecordingHandler
I 1112 14:09:55.537 THREAD30: /admin/logging => com.twitter.server.handler.LoggingHandler
I 1112 14:09:55.539 THREAD30: /admin/metrics => com.twitter.server.handler.MetricQueryHandler
I 1112 14:09:55.539 THREAD30: /admin/clients/ => com.twitter.server.handler.ClientRegistryHandler
I 1112 14:09:55.539 THREAD30: /admin/servers/ => com.twitter.server.handler.ServerRegistryHandler
I 1112 14:09:55.539 THREAD30: /admin/files/ => com.twitter.server.handler.ResourceHandler
I 1112 14:09:55.540 THREAD30: /admin/registry.json => com.twitter.server.handler.RegistryHandler
I 1112 14:09:55.555 THREAD30: Serving admin http on 0.0.0.0/0.0.0.0:9990
I 1112 14:09:55.606 THREAD30: Finagle version 6.30.0 (rev=745578b931893c432e51da623287144e548cc489) built at 20151015-163818
java.lang.NoSuchMethodError: com.twitter.finagle.util.DefaultTimer$.twitter()Lcom/twitter/finagle/util/TimerFromNettyTimer;
    at com.twitter.finagle.zipkin.thrift.RawZipkinTracer$.apply$default$4(RawZipkinTracer.scala:59)
    at com.twitter.finagle.zipkin.thrift.SamplingTracer.<init>(ZipkinTracer.scala:186)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at com.twitter.finagle.util.LoadService$$anonfun$6.apply(LoadService.scala:245)
    at com.twitter.finagle.util.LoadService$$anonfun$6.apply(LoadService.scala:234)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
    at com.twitter.finagle.util.LoadService$.apply(LoadService.scala:234)
    at com.twitter.finagle.tracing.DefaultTracer$.<init>(Tracer.scala:137)
    at com.twitter.finagle.tracing.DefaultTracer$.<clinit>(Tracer.scala)
    at com.twitter.finagle.param.Tracer$$anonfun$9.apply(Params.scala:137)
    at com.twitter.finagle.param.Tracer$$anonfun$9.apply(Params.scala:137)
    at com.twitter.finagle.Stack$Param$$anon$3.default$lzycompute(Stack.scala:313)
    at com.twitter.finagle.Stack$Param$$anon$3.default(Stack.scala:313)
    at com.twitter.finagle.Stack$Params$Prms.apply(Stack.scala:362)
    at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
    at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
    at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
    at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
    at com.twitter.finagle.Stack$Module1$$anonfun$toStack$3.apply(Stack.scala:457)
    at com.twitter.finagle.Stack$Node.make(Stack.scala:254)
    at com.twitter.finagle.server.StdStackServer$$anon$1.<init>(StackServer.scala:210)
    at com.twitter.finagle.server.StdStackServer$class.serve(StackServer.scala:169)
    at com.twitter.finagle.Http$Server.serve(Http.scala:161)
    at com.twitter.finagle.Server$class.serve(Server.scala:117)
    at com.twitter.finagle.Http$Server.serve(Http.scala:161)
    at com.twitter.finagle.Server$class.serve(Server.scala:121)
    at com.twitter.finagle.Http$Server.serve(Http.scala:161)
    at i.f.workshop.finch.Todo$.main(Todo.scala:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:168)
    at com.twitter.app.App$$anonfun$nonExitingMain$3.apply(App.scala:167)
    at scala.Option.foreach(Option.scala:257)
    at com.twitter.app.App$class.nonExitingMain(App.scala:167)
    at i.f.workshop.finch.Todo$.nonExitingMain(Todo.scala:20)
    at com.twitter.app.App$class.main(App.scala:133)
    at i.f.workshop.finch.Todo$.main(Todo.scala:20)
    at i.f.workshop.finch.Todo.main(Todo.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sbt.Run.invokeMain(Run.scala:67)
    at sbt.Run.run0(Run.scala:61)
    at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Logger$$anon$4.apply(Logger.scala:85)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:745)
Exception thrown in main on startup

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 7 s, completed Nov 12, 2015 3:09:56 PM
```

**Comment by vkostyukov** [comment]
Thanks @mfirry! I just fixed it.
